ALTER TABLE {0}_DATATYPE ALTER COLUMN ID DROP IDENTITY;
ALTER TABLE {0}_LANGUAGE ALTER COLUMN ID DROP IDENTITY;
CREATE SEQUENCE DATATYPE_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 100;
CREATE SEQUENCE LANG_SEQ AS BIGINT START WITH 1 INCREMENT BY 1 CACHE 100;
