CREATE TABLE QUERY_GRAPHS(
		ID			{6} NOT NULL,
		DSID		{6} NOT NULL,
		SERVERID	{7}({4}) {3} NOT NULL,
		PRIMARY KEY (ID,DSID)
);
CREATE UNIQUE INDEX QG_DSID_ID ON QUERY_GRAPHS(DSID,ID);
CREATE INDEX QG_SERVERID ON QUERY_GRAPHS(SERVERID);