#*******************************************************************************
# Copyright (c) 2004, 2007 IBM Corporation and Cambridge Semantics Incorporated.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
#  File:        $Source: /cvsroot/slrp/boca/com.ibm.adtech.boca.model/sql/nodecentric/db2/createBocaTemporaryTables/Attic/GlitterTemporaryTables.ddl,v $
# Created by:  Matthew Roy ( <a href="mailto:mroy@us.ibm.com">mroy@us.ibm.com </a>)
# Created on:  9/30/05
# Revision:	$Id: GlitterTemporaryTables.ddl 229 2007-08-07 15:22:00Z mroy $
# 
# Contributors:
#     IBM Corporation - initial API and implementation
#     Cambridge Semantics Incorporated - Fork to Anzo
#*******************************************************************************
#
#
DECLARE GLOBAL TEMPORARY TABLE DEFAULTGRAPHS_TMP ( 
  ID {6} NOT NULL
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP;
CREATE INDEX SESSION.DEFAULTGRAPHS_IDX ON SESSION.DEFAULTGRAPHS_TMP (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE NAMEDGRAPHS_TMP ( 
  ID {6} NOT NULL
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP;
CREATE INDEX SESSION.NAMEDGRAPHS_IDX ON SESSION.NAMEDGRAPHS_TMP (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMPGRAPHS ( 
  ID {6} NOT NULL 
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP;
CREATE INDEX SESSION.TEMPGRAPHS_IDX ON SESSION.TEMPGRAPHS (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMP_COLUMNS(
	C0				{6},
	C1				{6},
	C2				{6},
	C3				{6},
	C4				{6},
	C5				{6},
	C6				{6},
	C7				{6},
	C8				{6},
	C9				{6},
	C10				{6},
	C11				{6},
	C12				{6},
	C13				{6},
	C14				{6},
	C15				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;

DECLARE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT0(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;
CREATE INDEX SESSION.CONSTRAINT0_IDX ON SESSION.TEMP_CONSTRAINT0 (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT1(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;
CREATE INDEX SESSION.CONSTRAINT1_IDX ON SESSION.TEMP_CONSTRAINT1 (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT2(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;
CREATE INDEX SESSION.CONSTRAINT2_IDX ON SESSION.TEMP_CONSTRAINT2 (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT3(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;
CREATE INDEX SESSION.CONSTRAINT3_IDX ON SESSION.TEMP_CONSTRAINT3 (ID) COLLECT STATISTICS;
