exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_B' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_TL' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_L' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_LL' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_LTL' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_LU' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_U' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'NAMEDGRAPHS' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'NAMEDGRAPHS_NR' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'LASTTRANSACTIONTIME' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'TRANSACTIONTIME' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_DATATYPE' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'ANZO_LANGUAGE' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'STATEMENTS' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'STATEMENTS_NR' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'GLITTERUNIT' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.GATHER_TABLE_STATS(ownname=> user,tabname=> 'SERVER' ,estimate_percent=> DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=> DBMS_STATS.AUTO_CASCADE,degree=> null,no_invalidate=> DBMS_STATS.AUTO_INVALIDATE,granularity=> 'AUTO',method_opt=> 'FOR ALL COLUMNS SIZE AUTO');
exec DBMS_STATS.SET_TABLE_STATS(user, 'ANZO_USED_IDS', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'LOCKED_GRAPHS', numrows=>10, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'DEFAULTGRAPHS_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'NAMEDGRAPHS_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMPGRAPHS', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMP_COLUMNS', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'SUBJECT_IDS_TEMP', numrows=>10, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'PREDICATE_IDS_TEMP', numrows=>10, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'OBJECT_IDS_TEMP', numrows=>10, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'NAMEDGRAPH_IDS_TEMP', numrows=>10, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'ID_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'RES_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'LIT_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'STMTS_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'NGR_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'STMTS_REP_TMP', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMP_CONSTRAINT0', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMP_CONSTRAINT1', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMP_CONSTRAINT2', numrows=>1000, numblks=>4);
exec DBMS_STATS.SET_TABLE_STATS(user, 'TEMP_CONSTRAINT3', numrows=>1000, numblks=>4);
exit;