ALTER TABLE {0}_DATATYPE  MODIFY ID {6};
ALTER TABLE {0}_LANGUAGE  MODIFY ID {6};
CREATE SEQUENCE LANG_SEQ    START WITH 1 INCREMENT BY 1 CACHE 20000;
CREATE SEQUENCE DATATYPE_SEQ  START WITH 1 INCREMENT BY 1 CACHE 20000;
