#*******************************************************************************
# Copyright (c) 2004, 2007 IBM Corporation and Cambridge Semantics Incorporated.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
#  File:        $Source: /cvsroot/slrp/boca/com.ibm.adtech.boca.common/sql/nodecentric/db2/createTemporaryTables/tempTables.ddl,v $
# Created by:  Matthew Roy ( <a href="mailto:mroy@us.ibm.com">mroy@us.ibm.com </a>)
# Created on:  9/30/05
# Revision:    $Id: tempTables.ddl 178 2007-07-31 14:22:33Z mroy $
# 
# Contributors:
#     IBM Corporation - initial API and implementation
#     Cambridge Semantics Incorporated - Fork to Anzo
#*******************************************************************************
#
DECLARE GLOBAL TEMPORARY TABLE ID_TMP (
	ID		{6},
	ENTRYID	{6},
	TYPE 	{5}
) ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP_RDB;


DECLARE GLOBAL TEMPORARY TABLE RES_TMP (
	ENTRYID	{6},
	VALUE	{7}({4}) {3}
) ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP_RDB;

DECLARE GLOBAL TEMPORARY TABLE LIT_TMP (
	ENTRYID	{6},
	VALUE		{7}({4}) {3},
	MODIFIER_ID	{6}
) ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE IN USR_TBSP_RDB;


DECLARE GLOBAL TEMPORARY TABLE STMT_TMP (
    ID                BIGINT,
    METADATA        SMALLINT NOT NULL,
    NAMEDGRAPHID    BIGINT NOT NULL,
    SUBJ               BIGINT NOT NULL,
    PROP               BIGINT NOT NULL,
    OBJ                BIGINT NOT NULL
) ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;;

DECLARE GLOBAL TEMPORARY TABLE QUERY (
    NAMEDGRAPHID    BIGINT,
    SUBJ               BIGINT,
    PROP               BIGINT,
    OBJ                BIGINT
) ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;;
#CREATE INDEX SESSION.QUERY_TMP_IDX ON SESSION.QUERY (NAMEDGRAPHID,SUBJ,PROP,OBJ) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMP_COLUMNS(
    C0                BIGINT,
    C1                BIGINT,
    C2                BIGINT,
    C3                BIGINT,
    C4                BIGINT,
    C5                BIGINT,
    C6                BIGINT,
    C7                BIGINT,
    C8                BIGINT,
    C9                BIGINT,
    C10                BIGINT,
    C11                BIGINT,
    C12                BIGINT,
    C13                BIGINT,
    C14                BIGINT,
    C15                BIGINT
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;;
#CREATE INDEX SESSION.TC0_IDX ON SESSION.TEMP_COLUMNS (C0) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC1_IDX ON SESSION.TEMP_COLUMNS (C1) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC2_IDX ON SESSION.TEMP_COLUMNS (C2) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC3_IDX ON SESSION.TEMP_COLUMNS (C3) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC4_IDX ON SESSION.TEMP_COLUMNS (C4) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC5_IDX ON SESSION.TEMP_COLUMNS (C5) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC6_IDX ON SESSION.TEMP_COLUMNS (C6) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC7_IDX ON SESSION.TEMP_COLUMNS (C7) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC8_IDX ON SESSION.TEMP_COLUMNS (C8) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC9_IDX ON SESSION.TEMP_COLUMNS (C9) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC10_IDX ON SESSION.TEMP_COLUMNS (C10) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC11_IDX ON SESSION.TEMP_COLUMNS (C11) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC12_IDX ON SESSION.TEMP_COLUMNS (C12) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC13_IDX ON SESSION.TEMP_COLUMNS (C13) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC14_IDX ON SESSION.TEMP_COLUMNS (C14) COLLECT STATISTICS;
#CREATE INDEX SESSION.TC15_IDX ON SESSION.TEMP_COLUMNS (C15) COLLECT STATISTICS;


DECLARE GLOBAL TEMPORARY TABLE DEFAULTGRAPHS_TMP ( 
  ID BIGINT NOT NULL
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;
#CREATE INDEX SESSION.DEFAULTGRAPHS_IDX ON SESSION.DEFAULTGRAPHS_TMP (ID) COLLECT STATISTICS;


DECLARE GLOBAL TEMPORARY TABLE NAMEDGRAPHS_TMP ( 
  ID BIGINT NOT NULL
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;
#CREATE INDEX SESSION.NAMEDGRAPHS_IDX ON SESSION.NAMEDGRAPHS_TMP (ID) COLLECT STATISTICS;

DECLARE GLOBAL TEMPORARY TABLE TEMPGRAPHS ( 
  ID BIGINT NOT NULL
) ON COMMIT PRESERVE ROWS NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP_RDB;

CREATE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT0(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;

CREATE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT1(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;

CREATE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT2(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;

CREATE GLOBAL TEMPORARY TABLE TEMP_CONSTRAINT3(
	ID				{6}
)ON COMMIT PRESERVE ROWS  NOT LOGGED ON ROLLBACK DELETE ROWS WITH REPLACE in USR_TBSP;

