PREFIX : <http://example.org/>
# note, this is almost never right, since it puts the aggregate multiple times
# with each individual solution from the group
SELECT ?o ?count WHERE { 
    {
		:s1 :p1 ?o .
		LET( ?count := COUNT(?o)) .
	} UNION {
		:s2 :p2 ?o .
		LET( ?count := COUNT(?o)) .
	}
}